# Generated by Django 2.2.5 on 2019-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=12)),
                ('field2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
