# Generated by Django 2.2.5 on 2019-11-20 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191002_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='optional',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('S', 'Scinece&Tech'), ('F', 'Fiction'), ('B', 'Biography'), ('T', 'Travel'), ('O', 'Other')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(1, 'Regular member'), (2, 'Premium Member'), (3, 'Guest Member')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='myapp.Member'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 17, 38, 10, 501887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='USA', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Book')),
            ],
        ),
    ]
