# Generated by Django 2.2.5 on 2019-12-06 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191204_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(default='icon.jpg', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 6, 22, 8, 29, 892853, tzinfo=utc)),
        ),
    ]
